name: twnsqr
description: A community platform for local activities

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/fonts/
  fonts:
    - family: SFPRO
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf
          weight: 500

